SET(CF_HAVE_CGAL 0)

FIND_PATH(CGAL_INCLUDE_DIR CGAL
	DOC "Directory where the CGAL header directory is located"
	)
MARK_AS_ADVANCED(CGAL_INCLUDE_DIR)

FIND_LIBRARY(CGAL_LIBRARY CGAL
	DOC "The CGAL library"
	)
MARK_AS_ADVANCED(CGAL_LIBRARY)

IF(CGAL_INCLUDE_DIR AND CGAL_LIBRARY)
	SET(CF_HAVE_CGAL 1)
ENDIF(CGAL_INCLUDE_DIR AND CGAL_LIBRARY)

