SET(CF_HAVE_GOOGLE_PERFTOOLS 0)

FIND_PATH(GOOGLE_PERFTOOLS_INCLUDE_DIR google
	DOC "Directory where the google directory, containing the perftools headers, is located"
	)
MARK_AS_ADVANCED(GOOGLE_PERFTOOLS_INCLUDE_DIR)

FIND_LIBRARY(GOOGLE_PERFTOOLS_LIBRARY profiler
	DOC "The Google profiler library"
	)
MARK_AS_ADVANCED(GOOGLE_PERFTOOLS_LIBRARY)

IF(GOOGLE_PERFTOOLS_INCLUDE_DIR AND GOOGLE_PERFTOOLS_LIBRARY)
	SET(CF_HAVE_GOOGLE_PERFTOOLS 1)
ENDIF()

